name: ms-appt
channels:
  - pytorch
  - conda-forge
  - bioconda
dependencies:
  - python=3.9.16
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - numpy=1.24.3
  - pandas=2.0.3
  - scikit-learn=1.3.0
  - matplotlib=3.7.1
  - seaborn=0.12.2
  - pyyaml=6.0
  - pip:
    - transformers==4.30.0
    - h5py==3.8.0
    - tqdm==4.65.0
    - tensorboard==2.13.0
    - torch-tb-profiler==0.4.1